#!/usr/bin/env python3
"""
INDRA Platform — Purge Synthetic Demo Data
Safely removes demo records generated by `scripts/seed_analytics_demo.py`:
  - verified_events with event_code LIKE 'DEMO-%'
  - raw_reports with docket LIKE 'R-DEMO%'

Does NOT touch genuine operational data (WX-% events, NDMA/SACHET alerts, real reports).

Usage:
  python3 scripts/purge_demo_data.py
  python3 scripts/purge_demo_data.py --dry-run
"""

import argparse
import asyncio
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

import asyncpg
from app.core.config import get_settings


async def purge(dry_run: bool = False):
    settings = get_settings()
    # asyncpg expects postgresql:// not postgresql+asyncpg://
    dsn = settings.DATABASE_URL.replace("postgresql+asyncpg://", "postgresql://")
    print(f"Connecting to database: {settings.POSTGRES_HOST}:{settings.POSTGRES_PORT}/{settings.POSTGRES_DB}")

    conn = await asyncpg.connect(dsn)
    try:
        # 1. Audit current counts
        counts = await conn.fetchrow("""
            SELECT
                COUNT(*) FILTER (WHERE event_code LIKE 'DEMO-%') AS demo_events,
                COUNT(*) FILTER (WHERE event_code NOT LIKE 'DEMO-%') AS real_events,
                (SELECT COUNT(*) FROM raw_reports WHERE docket LIKE 'R-DEMO%') AS demo_reports,
                (SELECT COUNT(*) FROM raw_reports WHERE docket NOT LIKE 'R-DEMO%' OR docket IS NULL) AS real_reports
            FROM verified_events;
        """)

        print("\n── Current Status ──")
        print(f"  Demo events (DEMO-%):     {counts['demo_events']}")
        print(f"  Real events (WX-%, etc):  {counts['real_events']}")
        print(f"  Demo reports (R-DEMO%):   {counts['demo_reports']}")
        print(f"  Real reports:             {counts['real_reports']}")

        if dry_run:
            print("\n[DRY RUN] No records were deleted.")
            return

        print("\n── Purging Demo Data ──")
        async with conn.transaction():
            # Delete demo raw_reports first
            del_reports = await conn.execute("DELETE FROM raw_reports WHERE docket LIKE 'R-DEMO%';")
            print(f"  ✓ Deleted raw_reports: {del_reports}")

            # Delete demo verified_events
            del_events = await conn.execute("DELETE FROM verified_events WHERE event_code LIKE 'DEMO-%';")
            print(f"  ✓ Deleted verified_events: {del_events}")

        # 2. Audit post-purge counts
        after_counts = await conn.fetchrow("""
            SELECT
                COUNT(*) FILTER (WHERE event_code LIKE 'DEMO-%') AS demo_events,
                COUNT(*) FILTER (WHERE event_code NOT LIKE 'DEMO-%') AS real_events,
                (SELECT COUNT(*) FROM raw_reports WHERE docket LIKE 'R-DEMO%') AS demo_reports,
                (SELECT COUNT(*) FROM raw_reports WHERE docket NOT LIKE 'R-DEMO%' OR docket IS NULL) AS real_reports
            FROM verified_events;
        """)

        print("\n── Post-Purge Verification ──")
        print(f"  Remaining demo events:    {after_counts['demo_events']} (expected: 0)")
        print(f"  Preserved real events:    {after_counts['real_events']}")
        print(f"  Remaining demo reports:   {after_counts['demo_reports']} (expected: 0)")
        print(f"  Preserved real reports:   {after_counts['real_reports']}")
        print("\n✅ Successfully purged all synthetic demo data. Operational data remains intact.")

    finally:
        await conn.close()


def main():
    parser = argparse.ArgumentParser(description="Purge INDRA demo data")
    parser.add_argument("--dry-run", action="store_true", help="Inspect counts without deleting")
    args = parser.parse_args()

    asyncio.run(purge(dry_run=args.dry_run))


if __name__ == "__main__":
    main()
